Fix: upload

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,16 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
       
+      # Print repository name - $GITHUB_REPOSITORY
+      - name: Print repository name
+        run: |
+         echo "Repository: $GITHUB_REPOSITORY"
+     
+      # Print GitHub run URL - $GITHUB_RUN_ID
+      - name: Print GitHub run URL
+        run: |
+          echo "Run URL: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+
       # 设置java环境
       - name: Set up Java for Android build
         uses: actions/setup-java@v3
@@ -157,15 +167,15 @@ jobs:
       - name: Build iOS App
         run: flutter build ios --release --no-codesign
 
-      # Set up Apple Certificate and Profile for signing
-      - name: Set up Signing Certificates and Provisioning Profiles
-        uses: apple-actions/import-codesign-certs@v3
-        with:
-          p12-file-base64: ${{ secrets.IOS_CERTIFICATE }}
-          p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
-          provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
-          keychain: 'tempKeychina'
-          keychain-password: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
+      # # Set up Apple Certificate and Profile for signing
+      # - name: Set up Signing Certificates and Provisioning Profiles
+      #   uses: apple-actions/import-codesign-certs@v3
+      #   with:
+      #     p12-file-base64: ${{ secrets.IOS_CERTIFICATE }}
+      #     p12-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
+      #     provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
+      #     keychain: 'tempKeychina'
+      #     keychain-password: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
 
       # Archive the iOS app for deployment or further actions
       - name: Archive the iOS App
@@ -186,12 +196,6 @@ jobs:
             -archivePath build/ios/archive/Runner.xcarchive \
             -exportOptionsPlist ios/ExportOptions.plist \
             -exportPath build/ios/ipa/snapmaker.ipa \
-    
-      - name: Upload build ios artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: ios-ipa
-          path: build/ios/ipa/snapmaker.ipa
 
       # flutter build ipa  --export-method: ad-hoc, development, enterprise
       # - name: Flutter build ipa and Export iOS IPA
@@ -203,14 +207,45 @@ jobs:
       #   run: |
       #     rm -f /tmp/certificate.p12
       #     rm -f /tmp/profile.mobileprovision
-    
+  
+  # 这些任务在 build 成功后运行，分别将 Android 和 iOS 的构建结果（APK 和 .xcarchive）上传为 GitHub Artifacts
+  android-deploy:
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.ref == 'refs/heads/main'
+    steps:
+      - name: Upload Android APK to GitHub
+        uses: actions/upload-artifact@v3
+        with:
+          name: app-release.apk
+          path: build/app/outputs/flutter-apk/app-release.apk
+
+  ios-deploy:
+    runs-on: macos-latest
+    needs: build
+    if: github.ref == 'refs/heads/main'
+    steps:
+
+      - name: Upload build ios artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: ios-ipa
+          path: build/ios/ipa/snapmaker.ipa
+
+      # Upload the dSYM file (Symbols for debugging)
+      - name: Upload dSYM
+        uses: actions/upload-artifact@v3
+        with:
+          name: ios-dsym
+          path: build/ios/archive/Runner.xcarchive/dSYMs/
+
   notify:
     runs-on: ubuntu-latest
-    # needs: [android-deploy, ios-deploy]  # 依赖于 android-deploy 和 ios-deploy 的执行结果
+    needs: [android-deploy, ios-deploy]  # 依赖于 android-deploy 和 ios-deploy 的执行结果
     steps:
-      # always() / success() || failure() 不论前面的 job 成功或失败都会执行
+      # always() / success() || failure() 不论前面的 job 成功或失败都会执行  $GITHUB_REPOSITORY $GITHUB_RUN_ID
       - name: Notify via Feishu
-        if: success()
+        if: success() || failure()
         run: |
           curl -X POST "$FEISHU_WEBHOOK_URL" \
             -H 'Content-Type: application/json' \
